In [2]:
#check numpy version
import numpy as np
np.__version__

'2.1.1'

In [ ]:
# numpy -- numericalpytho# 
# it is faster than list
#it is used when we want to use arrays so basically it do the work of arrays
#types of array -- 1d,2d,3d
# shape has to be maintained
# it is 50x faster than list 
#it is homogeneous use same data type


In [6]:
lst = [1,2,3,4,5]
ar1 =  np.array(lst)
ar1
print(type(ar1))

<class 'numpy.ndarray'>


In [7]:
lst = [1,2,"3",4,5]
ar1 =  np.array(lst)
ar1

array(['1', '2', '3', '4', '5'], dtype='<U21')

In [99]:
arr1 = np.array([1,2,3,4,5],ndmin=4)
arr1


array([[[[1, 2, 3, 4, 5]]]])

In [9]:
#range
arr = np.arange(1,11)
# print(arr)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [12]:
arr = np.zeros(3)
arr

array([0., 0., 0.])

In [ ]:
#2D array
arr2 = np.zeros((2,3)) # assumme it as a matrix
arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
arr3 = np.linspace(1,10,5)
arr3

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [17]:
arr3 = np.linspace(1,10,50)
arr3

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [ ]:
#convert 1D to 2D
arr4 = np.arange(1,31).reshape(6,5) #5*6=30 to when you reshape give it in the form of multiple of  the total no. you give in 1D
arr4


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
#random - random number generation, it is a module in numpy
#randint -  gives the random integer
arr5 = np.random.randint(1,100,10) # it is updated everytime you run it
arr5

array([17, 35, 94, 15, 92, 26, 29, 73,  1,  6], dtype=int32)

In [26]:
arr6  = np.random.random(9).reshape(3,3) # return random float in the range[0.0,1.0]
arr6

array([[0.40040573, 0.79718149, 0.99647844],
       [0.28052271, 0.28608247, 0.16396018],
       [0.9195834 , 0.78842643, 0.09306335]])

In [ ]:
arr7 = np.arange(60).reshape(3,20)
arr7.shape     # shape tells you rows and coloumn
arr7.dtype     # tells the data type od the elements in the array
arr7.size      # tells the size
arr7.ndim        # tells the dimension


[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]]


In [ ]:
arr7 = np.arange(60).reshape(3,20)
arr7.ndim 

2

In [35]:
#multidimension array convert 1D
arr7.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [36]:
arr7.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [38]:
#transpose reverse rows to coloumn and vice versa
arr7 = np.arange(60).reshape(3,20)
print(arr7.shape)

arr8 = arr7.T.shape
arr8

(3, 20)


(20, 3)

In [43]:
#indexing and slicing
arr9 = np.arange(20)

arr9
arr9[5] 

np.int64(5)

In [44]:
ar = [1,2,3,4,5]
ar[0]

1

In [ ]:


ar[1:3:2]

[2]

In [ ]:
#2D -- [row start:row end ,coloumn start:column end]
arr7 = np.arange(60).reshape(12,5)
arr7

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [54]:
arr7[3:6]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [ ]:
# arr7[3:6,2:]

array([[17, 18, 19],
       [22, 23, 24],
       [27, 28, 29]])

In [59]:
arr7[3:6,2:]

array([[17, 18, 19],
       [22, 23, 24],
       [27, 28, 29]])

In [ ]:
arr7[3:4,2:3] 

array([[17]])

In [87]:
arr7[3:4,2:3]  = 100
arr7

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16, 100,  18,  19],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [88]:
np.max(arr7)

np.int64(100)

In [89]:
np.min(arr7)
np.sum(arr7)
np.mean(arr7)
np.median(arr7)
np.std(arr7)

np.float64(19.44830041131844)

In [92]:
arr7.sort()
arr7

array([[  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  18,  19, 100],
       [ 20,  21,  22,  23,  24],
       [ 25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34],
       [ 35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44],
       [ 45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59]])

In [ ]:
arr7 = arr7[3:4,2:3] 
arr7.argsort()    # its sorts acc to the inmdex number like 1 is on [2]

array([2, 0, 1, 3])

In [66]:
arr7[8:10,3:5][0][0]

np.int64(43)

In [75]:
arr7[::-1]

array([[ 55,  56,  57,  58,  59],
       [ 50,  51,  52,  53,  54],
       [ 45,  46,  47,  48,  49],
       [ 40,  41,  42,  43,  44],
       [ 35,  36,  37,  38,  39],
       [ 30,  31,  32,  33,  34],
       [ 25,  26,  27,  28,  29],
       [ 20,  21,  22,  23,  24],
       [ 15,  16, 100,  18,  19],
       [ 10,  11,  12,  13,  14],
       [  5,   6,   7,   8,   9],
       [  0,   1,   2,   3,   4]])

In [ ]:
arr7[::-1,::-1] #reverse column and rows

array([[ 59,  58,  57,  56,  55],
       [ 54,  53,  52,  51,  50],
       [ 49,  48,  47,  46,  45],
       [ 44,  43,  42,  41,  40],
       [ 39,  38,  37,  36,  35],
       [ 34,  33,  32,  31,  30],
       [ 29,  28,  27,  26,  25],
       [ 24,  23,  22,  21,  20],
       [ 19,  18, 100,  16,  15],
       [ 14,  13,  12,  11,  10],
       [  9,   8,   7,   6,   5],
       [  4,   3,   2,   1,   0]])

In [ ]:
#3d array
arr9 = np.arange(225).reshape(3,15,5)  #syntax[table divided,row,column]
arr9


array([[[  0,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24],
        [ 25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34],
        [ 35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44],
        [ 45,  46,  47,  48,  49],
        [ 50,  51,  52,  53,  54],
        [ 55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64],
        [ 65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74]],

       [[ 75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94],
        [ 95,  96,  97,  98,  99],
        [100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114],
        [115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124],
        [125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134],
        [135, 136, 137, 138, 139],
        [140, 141,

In [81]:
##slicing in #D arrray
#stntax --
#[table start : table end : table skip, row start : row end : row skip, col start:col end :col skip]
arr9[1]

array([[ 75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84],
       [ 85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94],
       [ 95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114],
       [115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124],
       [125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134],
       [135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144],
       [145, 146, 147, 148, 149]])

In [ ]:
arr9[0:,1:4]

array([[[  5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14],
        [ 15,  16,  17,  18,  19]],

       [[ 80,  81,  82,  83,  84],
        [ 85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94]],

       [[155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164],
        [165, 166, 167, 168, 169]]])

In [83]:
arr9[0:,1:4,2:4]

array([[[  7,   8],
        [ 12,  13],
        [ 17,  18]],

       [[ 82,  83],
        [ 87,  88],
        [ 92,  93]],

       [[157, 158],
        [162, 163],
        [167, 168]]])

In [86]:
arr9[0: 1,5:6,0:3]

array([[[25, 26, 27]]])

In [96]:
arr11 = np.array([2,5,1,9])
arr11*2

array([ 4, 10,  2, 18])

In [ ]:
arr11 = np.array([2,5,1,9])
arr12 = np.array([2,5,1,9])
